### PR TITLE
Upgrade ember-test-selectors and ember-cli-htmlbars

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
ember-cli-htmlbars: https://github.com/ember-cli/ember-cli-htmlbars/blob/master/CHANGELOG.md
ember-test-selectors: https://github.com/simplabs/ember-test-selectors/blob/master/CHANGELOG.md

The deprecation I'm wanting to eliminate:
 - from ember-test-selectors:
    - #758 Remove deprecated TransformTestSelectorParamsToHashPairs transform
       DEPRECATION: Using class based template compilation plugins is deprecated, please update to the functional style: TransformTestSelectorParamsToHashPairs [deprecation id: template-compiler.registerPlugin]

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
gotta fix the ember 4+ stuff, one sec

**Comment by NullVoxPopuli** [comment]
Now I have to deal with:
```
Global error: Uncaught Error: Could not find module `@ember/application/deprecations` imported from `@ember/test-helpers/setup-rendering-context` at http://localhost:7357/assets/vendor.js, line 259
```
:sweat_smile:

**Comment by NullVoxPopuli** [comment]
Now we need this: code: https://github.com/ember-cli/ember-cli/blob/b24b73b388934796ca915ca665b48a27c857199b/lib/utilities/ember-app-utils.js#L130

rather than the version that does `Ember.assert`, so ember-cli gets upgraded now too (only affects tests)

**Comment by NullVoxPopuli** [comment]
that's all for now -- stuck on errors with ember 4+ -- maybe ya'll can handle it from there

**Comment by mixonic** [comment]
Wow, I just saw this, but there are a **lot** of changes outside of ember-test-selectors and ember-cli-htmlbars getting bumped. I've landed those two items in:

* https://github.com/Addepar/ember-json-viewer/pull/19
* https://github.com/Addepar/ember-json-viewer/pull/20

And I think that leaves this PR as something more like "add 3.28 to the CI suite, improve Ember 4 compat".

Regardless I'm going to go ahead and close it for now. 100% work will continue along these lines, and will likely use this PR as a starting point. I'd be very open to a PR adding Ember 3.28 to the CI suite and getting it green, then we can look at Ember 4 as a distinct effort.

Thanks for this spike @NullVoxPopuli! Onward!

**Pull request closed without merging**
